apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: front-conf
          configMap:
            name: front-conf
      containers:
        - name: frontend
          image: florencia123/front
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
                - name: front-conf
                  mountPath: /usr/share/nginx/html/.env
                  subPath: .env