apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: florencia123/front
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: VUE_APP_ENV_BACK_SERVICE_BACK_IP
              valueFrom: 
                configMapKeyRef:
                  name: front-conf
                  key: ip
            - name: VUE_APP_ENV_BACK_SERVICE_BACK_PORT
              valueFrom:
                configMapKeyRef:
                  name: front-conf
                  key: port