apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: florencia123/front
          volumeMounts:
          - name: config-volume
            mountPath: /app/public/config.js
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: BACK_IP
              valueFrom:
                configMapKeyRef:
                  name: front-conf  
                  key: ip
            - name: BACK_PORT
              valueFrom:
                configMapKeyRef:
                  name: front-conf 
                  key: port
      volumes:
        - name: config-volume
          configMap:
            name: vue-config